apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"60e54cfd-0f91-11ea-9a58-221600a55839","leaseDurationSeconds":15,"acquireTime":"2019-11-25T15:19:50Z","renewTime":"2019-11-25T15:19:52Z","leaderTransitions":0}'
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: hostpath
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkinsnew
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.9.4
  name: jenkinsnew
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/jenkinsnew
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: pvc-05bd9d34-0f97-11ea-82a0-02128fb55632
status: {}
