apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"nexus-svc"},"name":"nexus","namespace":"default"},"spec":{"ports":[{"name":"nexusport","port":8081,"targetPort":8081}],"selector":{"app":"nexus"},"type":"LoadBalancer"}}
  creationTimestamp: null
  labels:
    app: nexus-svc
  name: nexus
  selfLink: /api/v1/namespaces/default/services/nexus
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: nexusport
    nodePort: 32173
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: nexus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
