apiVersion: v1
data:
  jenkins-admin-password: b0FIbk5aMWZIUA==
  jenkins-admin-user: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkinsnew
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.9.4
  name: jenkinsnew
  selfLink: /api/v1/namespaces/default/secrets/jenkinsnew
type: Opaque