vagrant@k8s-master:~$ cat deployment.extensions_nexus-sonatype-nexus.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    app: sonatype-nexus
    chart: sonatype-nexus-1.21.0
    fullname: nexus-sonatype-nexus
    heritage: Tiller
    release: nexus
  name: nexus-sonatype-nexus
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nexus-sonatype-nexus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonatype-nexus
      release: nexus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sonatype-nexus
        release: nexus
    spec:
      containers:
      - env:
        - name: install4jAddVmParams
          value: -Xms1200M -Xmx1200M -XX:MaxDirectMemorySize=2G -XX:+UnlockExperimentalVMOptions
            -XX:+UseCGroupMemoryLimitForHeap
        image: quay.io/travelaudience/docker-nexus:3.17.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: nexus
        ports:
        - containerPort: 5003
          name: nexus-docker-g
          protocol: TCP
        - containerPort: 8081
          name: nexus-http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /nexus-data
          name: nexus-sonatype-nexus-data
        - mountPath: /nexus-data/backup
          name: nexus-sonatype-nexus-backup
      - env:
        - name: ALLOWED_USER_AGENTS_ON_ROOT_REGEX
          value: GoogleHC
        - name: CLOUD_IAM_AUTH_ENABLED
          value: "false"
        - name: BIND_PORT
          value: "8080"
        - name: ENFORCE_HTTPS
          value: "false"
        - name: NEXUS_DOCKER_HOST
        - name: NEXUS_HTTP_HOST
        - name: UPSTREAM_DOCKER_PORT
          value: "5003"
        - name: UPSTREAM_HTTP_PORT
          value: "8081"
        - name: UPSTREAM_HOST
          value: localhost
        image: quay.io/travelaudience/docker-nexus-proxy:2.5.0
        imagePullPolicy: IfNotPresent
        name: nexus-proxy
        ports:
        - containerPort: 8080
          name: nexus-proxy
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nexus-sonatype-nexus-data
        persistentVolumeClaim:
          claimName: nexus-sonatype-nexus-data
      - emptyDir: {}
        name: nexus-sonatype-nexus-backup
status: {}
vagrant@k8